clang++.exe .\cpp\code.cpp -o code.exe
type ex1 | .\code.exe
type ex2 | .\code.exe
type ex3 | .\code.exe
type ex4 | .\code.exe
type ex5 | .\code.exe
type ex11 | .\code.exe
type ex12 | .\code.exe
type ex31 | .\code.exe
type ex32 | .\code.exe
type ex33 | .\code.exe
